tasks:
  - name: sonarqube-test-bundle
    description: Create the UDS bundle with Sonarqube and its dependencies
    actions:
      - task: sonarqube-package
      - task: dependency-package
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}

  - name: sonarqube-package
    description: Create the UDS Sonarqube Zarf Package
    actions:
      - cmd: zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE} --flavor registry1

  - name: dependency-package
    description: Create the Dependency Zarf Package(s)
    actions:
      - cmd: |
          for dependency in postgres; do
            zarf package create test/${dependency}/ --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom
          done
