tasks:
  - name: sonarqube-package
    actions:
      - description: Deploy the UDS Sonarqube Zarf Package
        cmd: zarf package deploy zarf-package-sonarqube-${UDS_ARCH}-*.tar.zst --confirm --no-progress

  - name: sonarqube-test-bundle
    actions:
      - description: Deploy the UDS bundle with Sonarqube and its dependencies
        cmd: UDS_CONFIG=bundle/uds-config.yaml uds deploy bundle/uds-bundle-sonarqube-test-${UDS_ARCH}-*.tar.zst --confirm --no-progress -l debug
