name: Setup

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    paths:
      - ".github/**"
      - "bundle/**"
      - "values/**"
      - "tasks/**"
      - "src/**"
      - "chart/**"
      - "tasks.yaml"
      - "zarf.yaml"

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  id-token: write # Needed for OIDC-related operations.
  contents: read # Allows reading the content of the repository.
  pull-requests: read # Allows reading pull request metadata.

# Default settings for all run commands in the workflow jobs.
defaults:
  run:
    shell: bash -e -o pipefail {0} # Ensures that scripts fail on error and pipefail is set.

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    name: Test
    strategy:
      matrix:
        flavor: [upstream-ce, registry1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Environment setup
        uses: ./.github/actions/setup
      
      - name: Iron Bank Login
        if: ${{ matrix.flavor == 'registry1' }}
        run: zarf tools registry login -u "${{secrets.IRON_BANK_ROBOT_USERNAME}}" -p "${{secrets.IRON_BANK_ROBOT_PASSWORD}}" registry1.dso.mil

      - name: Create test bundle
        run: uds run create-test-bundle --set FLAVOR=${{ matrix.flavor }}

      - name: Setup cluster
        run: uds run setup-cluster
      
      - name: Deploy test bundle
        run: uds run deploy-test-bundle

      - name: Test package
        run: uds run test-package

      - name: Cleanup
        if: always()
        run: uds run cleanup

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
